apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-publish
spec:
  template:
    spec:
      containers:
        - name: rabbitmq-client
          image: satyazzz123/keda-rabbitmq:latest 
          imagePullPolicy: Always
          command:
            [
              "send",
              "amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672",
              "300",
            ]
      restartPolicy: Never
  backoffLimit: 4
